---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: devops
spec:
  encryptedData:
    my-config-file.yml: AgB8/9ouoXLl1XZY5Re0JUM3/WPF38IGLmRDUvMMpU80yROHt3U41tLQzAnpSZ+YyNX+m7uIYa9u8jnJ7TtEokZpuLzTh8QgiS+3KF6ynqmwZT9v3owAEDX6wjhhMOcf/e1mrWGrKTvsIjdHZoDbNSwYXcakxijLo7a2fVkvjwwzioawjoZK0WTSeObUn1wEhSatH0C4NtyEdNu/z8iVIRAj2eIPZKvxoLFh3NdPEs0SCYE2PpAUjKo38EYFftyTukkpw/Qdb+R1pD2KDn6AltGiEXdc/s7OtMpoGye4HCwYhFzeyJ+/fdd6DEXF+DyOXoTWbwgifOjMn69Y8VxRCdspMpU0jHX9uLUzAi1hGUeL5bMFAodnXUa5Uf17/P8WBKWQbBUtcyHQIeJT9Gacf2e6tel3Z5RdFZAycCix3iQeZjOHvD+6ZG3c4SqTz2pv8xkJZnIVcofB8SLQrgPyLo1QJpCshXnq5vQl4MS+ZYyBWRYcjoMDrVTGPLUviBl/w223HoE5K4VF1K5a1KRRUQ436IdwLvBYIuIqYCFlGRLhg7DA0qjHe8s0G4YhVNI4DNp7UxX5oZ3BVWZtiTSsKcQYLKO/caN9myRfKqY4kCB1FsYjQA4p93Z0RoAo6Aq0qKF2scs/tqlTXxLGKWOvnOFUdmwIDaLCh6tbWvvGGLxxe5UY7KWZ2/h2ia0sEG0p+TnAgBNM25XspzkCxgs51qDhkF57kBQtO9SmqPZLPeJTJCfGQUOhx6MCM3npxBunUJRRabaDKA9e24Tn6gLwwAOjKRsURig7d0aLdlWgSPXiQidJL/oPrLKCi40G2vsPNMHMC5CLPEk7Du4=
  template:
    metadata:
      name: my-secret
      namespace: devops
