apiVersion: v1
kind: Secret
metadata:
  name: my-argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  # Change url, username, password with your own
  url: https://github.com/entermix123/devops-app-deployment
  username: entermix123
  password: github_pat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
