---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: devops-secret-blue
  namespace: devops
spec:
  encryptedData:
    devops-blue-html-text-one: AgA2xO0u6rpEwKOz9TsRWUaZBSkxBabXzxk5XgEA+giXTDdbpWFxyleNGQMkYKu0HR4rTvBfRwVnsa/LHjU+n2OzSsWCyNWWyfuvDTU4cbQD31w2nelAnPd3eZgIXX4k7ClYum0jtdXgNkR2LYmylrpv07v60athe+MpnZfHOkZX/LtqG6C7mMFbgwGfwR9idCeHy+CyyZDuBAVsqpbyW6rIpp75f2VhsXyl/rCtgehopw97TDopbZnnjNI496ZNQmMPvQiL952OVxR2RznAiKSOBh0pK7osxJSsObmS6V+HYhiXAuga3jZd/Q6WwHnep48KOlaB9xsALBj3+C4UZUBs6PClQ0jVDQmW89afQio6PD2axU1nkMyrv9JdUZp857q7f55nTvuG0IQm/3esttfLx59QQloB4MechvC1znvzO26Ijzthi45nffF8s39qb+kfsFgJ/qg+5d+csu+driL1bKqf8+vvgeD/yRBMtRiNgTUHuYzi09Pbb+ohHLfnCjVgaHBh4TDQ79GE8rbjO9bzTmiqfQUr+qby8T091nx/9S3l/f92klJfpK4vzI34ZTt4gbQ+oIBFqgGfZsiKpGXPOWD57+jfzUF6jOF5/Gbp/ksJE/QxSgH4skf/K41O1zAS6FSsVkZOCKfgwx7UFLixbx08xhguP4gQ+1684+VsAX2qYM4TYFtj/Q2JMcLQBQRYmBW9DvDV/JuTu/BCF7hF0ZsoGz2BqH+c6TWPeYsQ8cQCxK+bqdV47S5EJPZd
    devops-blue-html-text-two: AgAWdLAGG8oXzZ/6eLmA4U5SBjIPA5PBUfqeLkUi4iugjeJxdO/uqo7f7n4WN8U3gr8oKX++OIgHzAJDqOat54sP6jrNyckFDSxzUN6bR2Ukm5ou9OdbGQrc2QlOTaFD70a+J5eTjBuIUFjT9hwYgx3dwgWe5NbpLgzJ3OrIvZ+MXjaAfKVv7h3WLlW02l4wdJqCXT6je5YTId5vYWL4b91TDEiyLTusBTEbOJ8kQzdUsO3oO4LnAG0EJiRb41VSRiS3QGlGtIb7snWi9eFs/FmNgMQb34muvhK5FFBaK0eRnEk6bRSpCvNA94KMi7+csQJRzePzvbFMvY05nccFwZXs1MzCqHApNT9BpxiiFNBbz7WSFZN2hWXHmZj0//BOiDFt/cKBJ8uaabZIFj2gELFxMCASz+XxSYY/Wh05IZ7E4HendXlOUpeo0JQ3fe5CuByEKSCHzNuQHx27yhCL5RvjwO7y45F1GlQJ8p7Ajpwmf71W5uHTDysUquXz86R9f+t4mhVpDErykRFW/WGI9tHj8KrABsNK5FOaAj/yzfePZBN+Ecl9U+q0/R7kcpdzhSyLN9MRp1nkiwY0C/4MTifzjAfo2voPb41EvHzj7/A0tJ5DTqS7LLAED9O4okVgg2GcokNQ/FJtDsl7A7nyxt2h03cahCTK+PNP8S+GP3AKCuhHEcExFoDc6x+LkdDcV04IUi/OuOP1oD48Q/8fXAbM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: devops-secret-blue
      namespace: devops
