---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: devops-secret-blue
  namespace: devops
spec:
  encryptedData:
    devops-blue-html-text-one: AgCF60LYjOcmU3FnS20tiK8/fLiOcw1r+U6owlmW9ARsV7KNgA9yfuKwgLrJqV/fEyx1d2fUPUFMeLeyHaaCqzvAtk5RiBIyebT/Aqcd1ZJWo0UcLbjU9efJZwAjrmHuLGeXtiqns5g0xAGr89uglpQfKPwmKROzy+1PmP6iO2LhyaOIz/pIc90/uFWBkKymZf86JD9/K2KHV8gyZYJuXbjp8u7inOk3INqOj9IP3tkh+XZVK50UIESc0GOypkuG+GY0DDypybsaxbU2X47vk/VKRWHoavEqHM3yWDqThRxDKCbG+cnlUpQZZ7iqs8RByPZk2Rtw+++HZCXzC8G1Acwai80SKaZKYKHJNJY4sv5DgdFZLtz4MioeIgYrU6T/eotdpjZuQ1cFDp4ByJ/KBLZaXWHnPFtUepTh1YTGEtfWUERKS55oqIavrTGCwUJXtYN51kkweHZ/GU2WM+p4Snj9+C1EgodfrTzFOGQ19tZMGwyRCaWmkGtyPVtpPEQzuXey9WUT2BcifQLt1fsCAUPYNuRXbC5jiLLCJNLaVAI616dXh7FrUKYMNxPnJqUMjTpdDYKu8wgS7Su0AmkQp/+T/qOFoZmpZ86wsL6AUaZAcq0fYJW3ehxKzQGJ33frt+pcfgkf1d45+ldR2oFw6/vP9LLhum0R57iO/bo1M3vxULyVs32HGC4U59dJnJBG7OzL9C85srhQjtSHOHHIZeK1juHku+n0Q2/hvmpL4Q==
    devops-blue-html-text-two: AgAXM+ZP5yHT2IrHS6J5hfVjn2mAAU+uWlDrHBS0fuWc2+dRQ2PD83J5BxDWKMvHbPczlMZ/jFS1SQ82j+JR4Yg0p1mudq7XsUuAHIyv7dy9013Wj+K28I1DZAWFj/mX7mZ7jnHusdVchA7Y+pc5PJaQAAU6C/ZIEMQqcP0xO59G32Q7ebcJQXMNUX1cUhlnYGphu0DkTP7XaXXaxz1/scwvcJ+OpTLp3pzi2YT0SsdUx1WOgoyjlJdb0Fx2JUoIn/vnCTrgmBzHZbOiINP72LyGk16g2Yr6fEx5Wq5m+Wb4ngBu62ME7JW295SDzVBWs1Z3eWXbx7vBGDTZVm2wppsZvuCKXr4Jvfcvoa+EoAC4ypQ/YY4DpOXiwZoGpF2xzwiOMG+wJ4BCIVkFe8zEYW0T9EPPs9JTYS3xTvwudO4eaRf0rZUadK/6XWYNYXJ8VEt50kCTUMLnbUQ5hCOacvL8WPR0mWn5rFQeSLTJXHOu5QcIw4QUBUsPyFLE8PS6yoHCib5kqf5S5diCXAyqsn8nEsespJoWc/D39OoVnFsLj9C8IJyaBRwCqQhkYPXlYAFFh+W2YUFVqBBoeEIbh/gXqxL+Kh1/+AHX/qqlYdvK0MvTpaRY5SRIE4mm1d5qkxdAZOdg9Le9HSX3ROmeyow81cgphOMP496TIjb/m3EZih2gPOguDwU5FeH7hgKl/KBo8zQhsBGb+s9GYWGVQMjtUMv3lqdOAVn5yikRdiN8tBI3hZ2qHZrQzUDfpYlOY6T6ufM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: devops-secret-blue
      namespace: devops
